### ISSUE TITLE
When I test  it the "remove" function on click removes all rows not  just the one that was clicked.  

### ISSUE THREAD

**Issue by wksantiago** [CodeEngineTechnology/Serverless_Invoice_App#1]
On the final code restored from Github all OK, but when I test  it the "remove" function on click removes all rows not  just the one that was clicked.  Have tried to troubleshoot but not able.

I did "  console.log(id);" but it does not print selected

**Comment by CodeEngineTechnology** [comment]
Please  change the OK  Button to and see if you see the invoice.id 
<td><Button className="btn btn-lg btn-success" onClick={ () => this.remove(invoice.id)} > <FontAwesomeIcon icon={faThumbsUp} /> OK {invoice.id} </Button></td>

**Comment by wksantiago** [comment]
I made the following change:
<td><Button className="btn btn-lg btn-success" onClick={ () => this.remove(invoice.id)}> <FontAwesomeIcon icon={faThumbsUp} /> OK {invoice.id} </Button> </td>

But get same result when I press OK all rows disappear and on entry in console

**Comment by CodeEngineTechnology** [comment]
Do you see the Invoice ID next to the OK button before click on it ?

**Comment by wksantiago** [comment]
No this is the screenshot 
![image](https://user-images.githubusercontent.com/6191556/80013566-11b49280-849d-11ea-8cd2-51a9119e87eb.png)

**Comment by CodeEngineTechnology** [comment]
I think I know why :) Looks like react is not able to use the id field that you have provided as a unique key. (we are using invoice.id in line <tr key={invoice.id}>).
Let's make sure the Id field is an integer and it is unique. You can test the app using the following format. Please let me know the result

         invoices :  [
            {
                "id" : "100",
                "Vendor":"Hankook",
                "Amount" : "$18,000",
                "invoice" : "1123",
                "Date" : "08/21/2019"
            },

            {
                "id" : "200",
                "Vendor":"Hankook",
                "Amount" : "$18,000",
                "invoice" : "1123",
                "Date" : "08/21/2019"
            },

            {
                "id" : "300",
                "Vendor":"Hankook",
                "Amount" : "$18,000",
                "invoice" : "1123",
                "Date" : "08/21/2019"
            }
        ]

I hope this helps
Best 
Siamak

**Comment by wksantiago** [comment]
Same results

The information I provided as a unique key was cut an paste form the code in the github and also now what you submitted.

Thanks,

**Comment by CodeEngineTechnology** [comment]
The invoice object that you have in your screenshot looks different to me. I see that you have 4 invoices and one of them called IOPKL which I don't have in the source code. Please copy and paste the invoice object that I have in a sample and sent me the error

![error](https://user-images.githubusercontent.com/54181887/80128110-0ff4d880-854a-11ea-856f-2851842871ee.png)

Thanks!

**Comment by wksantiago** [comment]
yes indeed the data comes form my DynamoDB via the API

https://jzvg94nf71.execute-api.us-east-1.amazonaws.com/Dev

**Comment by wksantiago** [comment]
This is my table arrangement:
![image](https://user-images.githubusercontent.com/6191556/80133903-f2d10180-856b-11ea-950c-bcb2c0b13f15.png)

**Comment by CodeEngineTechnology** [comment]
Please change the Id to id
If you notice the invoice sample that I sent shows the lowercase id

**Comment by wksantiago** [comment]
Yes that was it in my DynamoDB table I had Id so I changed it to id.

Perfect all OK thanks for your help.

Would it be possible to get you contact since I am working on a serverless project.

**Comment by CodeEngineTechnology** [comment]
You are welcome!
Of course.
codeengine101@gmail.com
